apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: kbase
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Base cluster components
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kbase
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:ststefa/argoauto-l5ug.git
        revision: "HEAD"
        files:
          - path: kbase/clusters/*/*/kustomization.yaml
        values:
          clusterName: "{{index .path.segments 2}}"
          componentName: "{{index .path.segments 3}}"
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: "{{ .values.componentName }}"
      name: kbase-{{ .values.clusterName }}-{{ .values.componentName }}
      namespace: argocd
    spec:
      destination:
        #! The name of the target cluster as configured in ArgoCD
        name: "{{ .values.clusterName }}"
        #! Alternatively to "name", the target can be specified as a URL
        #server: "https://kubernetes.default.svc"
        #! The namespace must be set by the kbase component
        #namespace:
      project: kbase
      source:
        repoURL: git@github.com:ststefa/argoauto-l5ug.git
        targetRevision: "HEAD"
        path: "{{ .path.path }}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
