apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    includeCRDs: true
    # see here for version: https://bitnami.github.io/sealed-secrets/index.yaml
    version: 2.19.1
    repo: https://bitnami.github.io/sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    valuesFile: sealed-secrets-values.yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: example-secret-generator
      annotations:
        config.kubernetes.io/function: |
            exec:
              # ksops must be reachable by $PATH
              path: ksops
    files:
    #! A constant encryption key. Together with disabling rotation this allows multi-cluster secrets (i.e., secrets which are valid on multiple clusters)
    - sealed-secrets-bootstrap-key-sec.sops.yaml

resources:
  #! A ClusterRole to allow creation of SealedSecrets
  - sealed-secrets-creator-cr.yaml

patches:
#! The chart generates the name "sealed-secrets", but kubeseal's default is "sealed-secrets-controller" in the kube-system namespace. Rename it to the default to avoid having to specify additional args on every kubeseal invocation
- target:
    kind: Service
    name: sealed-secrets
  patch: |-
    - op: replace
      path: /metadata/name
      value: sealed-secrets-controller