apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#! Legacy non-helm approach
#resources:
#  - sealed-secrets-operator.yaml

helmCharts:
  - name: sealed-secrets
    includeCRDs: true
    # see here for version: https://bitnami-labs.github.io/sealed-secrets/index.yaml
    version: 2.17.3
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets-controller
    namespace: kube-system
    #valuesFile: sealed-secrets-values.yaml

resources:
  - secrets-creator-cr.yaml
