# Show CRDs, see `crd-reader.yaml`
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-all
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_admin
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_editor
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-reader
