creation_rules:
  - path_regex: bootstrap/argo-cd/patches/argocd-repo-creds.sops.yaml
    encrypted_regex: sshPrivateKey
    input_type: yaml
    hc_vault_transit_uri: https://vault.heldenzeit.net/v1/transit/keys/sops
  - path_regex: bootstrap/argo-cd/patches/argocd-sso.sops.yaml
    encrypted_regex: oidc.clientSecret
    input_type: yaml
    hc_vault_transit_uri: https://vault.heldenzeit.net/v1/transit/keys/sops
  # As a safety net, encrypt fields typically used in Secret objects. This rule
  # should not be used and is just for catching unencrypted secrets before
  #  commit. If you have a secret, add it explicitly above!
  # Make sure to not encrypt non-sensitive values as every encrypted value
  # makes things harder to understand.
  - path_regex: .*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    hc_vault_transit_uri: https://vault.heldenzeit.net/v1/transit/keys/sops
