apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

helmCharts:
  - name: traefik
    includeCRDs: true
    #version: 4.11.0
    repo: https://traefik.github.io/charts
    releaseName: "kbase"
    valuesFile: traefik-values.yaml
    namespace: traefik

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: example-secret-generator
      annotations:
        config.kubernetes.io/function: |
            exec:
              # ksops must be reachable by $PATH
              path: ksops
    files:
    - traefik-namecheap-token.sops.yaml
    - traefik-tls-secret.sops.yaml

resources:
  - traefik-namespace.yaml
  - traefik-tls-store.yaml
