apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#! TODO: Disabled for now until all components move to traefik ns. Not currently possible due to my use of k3s embedded traefik. Disable that and factor it out to here.
#namespace: traefik

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: example-secret-generator
      annotations:
        config.kubernetes.io/function: |
            exec:
              # ksops must be reachable by $PATH
              path: ksops
    files:
    - namecheap-api-token.sops.yaml
    - tls-secret.sops.yaml

resources:
  - namespace.yaml
  - tls-store.yaml
