apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

#generators:
#  - |
#    apiVersion: viaduct.ai/v1
#    kind: ksops
#    metadata:
#      name: example-secret-generator
#      annotations:
#        config.kubernetes.io/function: |
#            exec:
#              # ksops must be reachable by $PATH
#              path: ksops
#    files:
#    - namecheap-api-token.sops.yaml
#    - tls-secret.sops.yaml

resources:
  - namespace.yaml
#  - tls-store.yaml
