apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:cZlW3R03DghtBpIoFJnHSpC4GZyH78R541Ne7zbqTGE=,iv:FiAO5nAhA1gxiC/I7aoi3tYDy847oxhB3dvv7FqNGuo=,tag:nX56dKJtLctuFpdOVvdtbw==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.heldenzeit.net
          engine_path: transit
          key_name: sops
          created_at: "2025-05-14T14:45:42Z"
          enc: vault:v1:tSX4JXGBLPoR7X8LGqxTp5JetLbJLmcKnKzkL7P5wcNhDRSabhWvV89xX1GmiLI7Pli5Qu3Bmk0vmlLw
    lastmodified: "2025-05-14T14:46:02Z"
    mac: ENC[AES256_GCM,data:pZRplU8gcTnVMmPivmM7mSFcBaRJPVu4xkcumJt9qWSn5ZKsTf+RQKu+/0KA1OKh7z3EnSpwRWzqGdqrgTMlt+YMq1Al+WzO8sTkoAzwE/IvklTRzQnX9kgEy+baiMvyQgRivYOm1TEG/2KkpNmahexTB6hZiMniydy2dqiLSIM=,iv:NrIUuMchOWdm4cg7cf4iYGBIwOe90NGdwnAVfaY22ZQ=,tag:RjcBK/KgvtWtGjpunzOnpw==,type:str]
    encrypted_regex: api-token
    version: 3.10.1
