apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:cZlW3R03DghtBpIoFJnHSpC4GZyH78R541Ne7zbqTGE=,iv:FiAO5nAhA1gxiC/I7aoi3tYDy847oxhB3dvv7FqNGuo=,tag:nX56dKJtLctuFpdOVvdtbw==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.heldenzeit.net
          engine_path: transit
          key_name: sops
          created_at: "2025-05-14T14:45:42Z"
          enc: vault:v1:tSX4JXGBLPoR7X8LGqxTp5JetLbJLmcKnKzkL7P5wcNhDRSabhWvV89xX1GmiLI7Pli5Qu3Bmk0vmlLw
    lastmodified: "2025-05-16T09:47:50Z"
    mac: ENC[AES256_GCM,data:KBs0L910q4xUozSHmCZbNoVkv23zhL3vBRnnJQldwet6HwBvEBv8j4IBo5Y3m1GbAFtFnXDy8DfLRy8hyIlfO9N878TE7EadYABY6/ZwuYpQIRczjmfpbvpqz+9WgESmvQ7Hnzb8NEKW+OfBQvN0ScGk6TUPfUkOG+NqhQqMgIM=,iv:vE2G8ELj1i273/XX+0MHawqH4vwLVQosPxNkk7Fv3Rw=,tag:OEujE7hekJYEyz8wdiH+0g==,type:str]
    encrypted_regex: api-token
    version: 3.10.1
