apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-slow
parameters:
  subDir: 6wu4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-fast
parameters:
  subDir: 6wu4
