# see https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# URL format originates from go lib, see https://github.com/hashicorp/go-getter#url-format
# Using URL-style ref fails, tried
#- https://github.com/kubernetes/dashboard/aio/deploy/recommended.yaml?ref=v2.7.0
#- https://github.com/kubernetes/dashboard/aio/deploy?ref=v2.7.0
#- https://github.com/kubernetes/dashboard/blob/v2.7.0/aio/deploy/recommended.yaml
#- github.com/kubernetes/dashboard/aio/deploy/recommended.yaml?ref=v2.7.0
# Downloading file and using locally works. TODO: not understood
- recommended.yaml
# removed again, does not have desired effect
#- crb.yaml
# Create a ServiceAccount used for logging in
- user.yaml

# Changing ns does not fully work. Problems with ClusterRole(Binding)s
#namespace: dashboard
