#!/bin/bash
# Generate a ClusterRole granting read access (get, list, watch) to all CRD instances
# grouped by apiGroup with resources: ["*"]

echo "Get all CRDs from connected k8s cluster and extract unique apiGroups" >&2
apiGroups=$(kubectl get crds -o json | jq -r '.items[].spec.group' | sort -u)

echo "# Generated by $0 on $(date)"
echo "apiVersion: rbac.authorization.k8s.io/v1"
echo "kind: ClusterRole"
echo "metadata:"
echo "  name: crd-reader"
echo "rules:"
echo "  # Allow to see CRD definitions"
echo "  - apiGroups: [\"apiextensions.k8s.io\"]"
echo "    resources: [\"customresourcedefinitions\"]"
echo "    verbs: [\"get\", \"list\", \"watch\"]"
echo "  # Each apiGroup must be allowed explicitly"

# For each apiGroup, add a rule with resources: ["*"]
while read -r apiGroup; do
  printf "  - apiGroups: [\"%s\"]\n    resources: [\"*\"]\n    verbs: [\"get\", \"list\", \"watch\"]\n" "$apiGroup"
done <<< "$apiGroups"
