apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

helmCharts:
  #! See https://github.com/traefik/traefik-helm-chart/releases
  - name: traefik
    includeCRDs: true
    version: 37.0.0
    repo: https://traefik.github.io/charts
    releaseName: traefik
    valuesFile: traefik-values.yaml
    namespace: traefik

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: example-secret-generator
      annotations:
        config.kubernetes.io/function: |
            exec:
              # ksops must be reachable by $PATH
              path: ksops
    files:
    - traefik-secret-namecheap.sops.yaml
    #! Part of disabled tls-store for manual cert mgmt
    #- traefik-secret-tls.sops.yaml

resources:
  - traefik-ns.yaml
  #! Only use for manual secret mgmt. Wil override automatic acme certificates if enabled
  #- traefik-tls-store.yaml
  #! Manually managed and kustomizable dashboard ingress
  - traefik-ingressroute.yaml
