apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:CZt9JxDx2HwkqwfbSC5+PlU2KmmVc9MtvVeBtVqDJVE=,iv:Ese9IEiSH4GXe0qSnDOBdrHtO1Uhv9MPZaOsWRMVwfk=,tag:xQDUYkfVOC1LmNnAJffqfg==,type:str]
sops:
    encrypted_regex: api-token
    hc_vault:
        - created_at: "2026-04-13T14:45:42Z"
          enc: vault:v1:tSX4JXGBLPoR7X8LGqxTp5JetLbJLmcKnKzkL7P5wcNhDRSabhWvV89xX1GmiLI7Pli5Qu3Bmk0vmlLw
          engine_path: transit
          key_name: sops
          vault_address: https://bao.heldenzeit.net
    lastmodified: "2026-09-07T17:16:57Z"
    mac: ENC[AES256_GCM,data:rPNGle7i5o5qhprqN1m3TqNb1B0siOh/Ac5fWmzGZPKEs+Yn90wKGRvaNPHTQFhf/TrOm+1yBuKVim/RjvxqZWzUBHZ54Jj/wz1MIm7tmdMON57V0D88aIxEQLyglAV1pB9T4isUgrihCspWQYRr5QDaE0FUHkfiG4zC0opi5e0=,iv:dwrth7ae43INXyoLwLMhpPjyJjcUW763kIG/sfhAOcw=,tag:8XGtYaj884OrhU2DEs+GLA==,type:str]
    version: 3.13.3
