#! Instead of using the helm values (which cannot be made host-specific), define the IngressRoute manually so it can be kustomized
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
  - websecure
#! Use an invalid default to force kustomization in clusters
#  routes:
#  - kind: Rule
#    match: Host(`HasToBeSpecifiedInCluster`)
#    services:
#    - kind: TraefikService
#      name: api@internal
  tls:
    certResolver: letsencrypt-dns
