apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-editor
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-viewer
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
# Show nodes, see `node-reader.yaml`
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-reader-all
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_admin
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_editor
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-reader
---
# Show CRDs, see `crd-reader.yaml`
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-all
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_admin
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_editor
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: k8s_viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-reader
